### ISSUE TITLE
DPARN Pretrained Model Performance 

### ISSUE THREAD

**Issue by yugeshav** [Qinwen-Hu/dparn#8]
@Qinwen-Hu 

Hello

I have used the pretrained models of both DPARN and DPCRN and generated the POLQA, PESQ scores using my test database

I could see DPCRN performing better than DPARN!!

Is it Expected?

Regards
Yugesh

**Comment by Qinwen-Hu** [comment]
Hello, Yugesh.

I guess your DPCRN model is a 16-khz model? Full-band (48k) processing is a much more challenging task. Wide-band models can concentrate on processing the critical low-band and thus achieve a more competitive performance sometimes, especially on metrics like PESQ (Since we only have 8-khz and 16-khz PESQ).

In our experiment, the DPCRN, DPCRN-SCM, and DPARN-SCM models are all trained and evaluated on 48-khz signals, though PESQ and STOI scores are generated using the down-sampled clean and enhanced signals.

If the DPCRN model that you have used is trained on 16-khz data and directedly implemented on 48-khz signals, and still achieves better performance than the DPARN-SCM model, that would be an interesting discovery!

**Comment by yugeshav** [comment]
> Hello, Yugesh.
> 
> I guess your DPCRN model is a 16-khz model? Full-band (48k) processing is a much more challenging task. Wide-band models can concentrate on processing the critical low-band and thus achieve a more competitive performance sometimes, especially on metrics like PESQ (Since we only have 8-khz and 16-khz PESQ).
> 
> In our experiment, the DPCRN, DPCRN-SCM, and DPARN-SCM models are all trained and evaluated on 48-khz signals, though PESQ and STOI scores are generated using the down-sampled clean and enhanced signals.
> 
> If the DPCRN model that you have used is trained on 16-khz data and directedly implemented on 48-khz signals, and still achieves better performance than the DPARN-SCM model, that would be an interesting discovery!

@Qinwen-Hu Thanks for the clarification!
